plugins { id 'com.android.application' }
android {
 namespace 'io.github.gy7604.alarmtest'
 compileSdk 35
 defaultConfig { applicationId 'io.github.gy7604.alarmtest'; minSdk 23; targetSdk 35; versionCode 3; versionName '0.3-schedule-alarm' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
